### ISSUE TITLE
Not working with electron asar api

### ISSUE THREAD

**Issue by akashnimare** [jfmdev/simple-spellchecker#2]
It works pretty well but on packaging my app with electron-packager and asar it throws some path error -

![image](https://cloud.githubusercontent.com/assets/2263909/19665824/9f498cc6-9a64-11e6-80df-81970ba9d6b5.png)

Do you have any idea why it's failing? Here is my [app](https://github.com/zulip/zulip-electron)

**Comment by jfmdev** [comment]
Hi, it seems that the application is failing to found the file "en-US.dic" in the folder "node_modules/simple-spellchecker/dict".

Could you manually verify if this file is available?

**Comment by akashnimare** [comment]
Hey, it's not there. Here is the result of asar list app.asar 
https://gist.github.com/antifuchs/053004619431e83498bc469cbbedbd6e#file-asar-list-app-asar-L6202

**Comment by jfmdev** [comment]
It seems that you have the file `en-US.zip` (in folder `node_modules/simple-spellchecker/dict`) but the application if failing in unzip it.

So, for now, the solution is to manually unzip the following files:
```
/node_modules/simple-spellchecker/dict/de-DE.zip
/node_modules/simple-spellchecker/dict/en-GB.zip
/node_modules/simple-spellchecker/dict/en-US.zip
/node_modules/simple-spellchecker/dict/es-ES.zip
/node_modules/simple-spellchecker/dict/es-MX.zip
/node_modules/simple-spellchecker/dict/fr-FR.zip
/node_modules/simple-spellchecker/dict/nl-NL.zip
```

Later I'm going to check why the application might be failing for unzip the files automatically.

Regards

**Comment by akashnimare** [comment]
I can't manually unzip those files. I'm using [electron-packager](https://github.com/electron-userland/electron-packager) to pack my app which uses [asar](https://github.com/electron/asar) format under the hood.

**Comment by jfmdev** [comment]
Are you using them method `getDictionary()` or `getDictionarySync()`? Please note that `getDictionary()` can, automatically, unzip the dictionary files, while `getDictionarySync()` requires to the dictionaries to be already unzipped.  

Also, I assume that you can't unzip the files manually because they are in the `node_modules` folder, however you could move the dictionary files to a different folder, unzip them there and then indicate the path of this folder using the `folderPath` parameter.
