### ISSUE TITLE
New wordlist is created if setWord is called

### ISSUE THREAD

**Issue by alaksandarjesus** [jfmdev/simple-spellchecker#50]
Below on the first attempt, after testing, I get misspelled items. Works perfectly fine.

![image](https://github.com/jfmdev/simple-spellchecker/assets/4712552/3dd35395-da26-4980-872d-273b1e3d5b5f)

Now i add to wordList articel using setWordlist

I clear the inputs and retest the same input (note: not restarting the electron server)

![image](https://github.com/jfmdev/simple-spellchecker/assets/4712552/e756097c-013e-409a-be63-b25bef6f2483)

Now articel is added to wordlist. Error is gone. But the second line is throwing error.

**Comment by jfmdev** [comment]
Hi @alaksandarjesus,

Yes, that's expected, the `setWordList` function **replaces** the current list of words, it don't adds new words to the current list (otherwise the method should be called `appendWordList` or `addWordList`).

I you want to append words to current list you should do something like:

```js
var SpellChecker = require('simple-spellchecker');
SpellChecker.getDictionary("en-US", function(err, dictionary) {
    if(!err) {
       dictionary.wordlist.push("new_word");
        var misspelled = ! dictionary.spellCheck('new_word');
        console.log(misspelled);
    }
});    
```
