### ISSUE TITLE
Dictionary not found

### ISSUE THREAD

**Issue by markgandolfo** [jfmdev/simple-spellchecker#6]
```js
    const SpellChecker = require('simple-spellchecker');

    SpellChecker.getDictionary('fr-FR', (err, dictionary) => {
      if (err) {
        console.log('error', err);
      } else {
        const misspelled = ! dictionary.spellCheck(word);
        if (misspelled) {
          const suggestions = dictionary.getSuggestions(word);
          console.log(suggestions);
        }
      }
```

Output is:

```
error The dictionary could not be read, no file with the name "fr-FR" could be found
```

I've attempted a few Dictionaries 'en-GB', 'en-US', etc. all have the same error. Any ideas?

**Comment by jfmdev** [comment]
Hi Mark,

When no passing the `folder` parameter to the `getDictionary()` method, the library assumes that the dictionaries are in a `dict` folder (located in `__dirname`).

So I recommend you to either:
 * Verify which is the value of `__dirname` (you can do it by adding the line `console.log(__dirname);`) in order to be sure that the dictionaries are at the right folder.
 * Or to explicitly specify the dictionaries folder (e.g. `SpellChecker.getDictionary('fr-FR', "C:\something\dict", (err, dicti...`).

Regards

**Comment by markgandolfo** [comment]
Thanks!
