### ISSUE TITLE
fs is required but was removed from npm registry?

### ISSUE THREAD

**Issue by ts3li0t** [jfmdev/simple-spellchecker#8]
simple-spellchecker/index.js
/*
 * Copyright (c) 2016 José F. Maldonado
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. 
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

// Load dependencies.
const fs = require('fs');

[asdf]$ ll node_modules/fs
total 8
-rw------- 1 user user 2059 Apr 26 08:33 package.json
-rw------- 1 user user 328 May 13  2016 README.md

https://www.npmjs.com/package/fs
This package name is not currently in use, but was formerly occupied by another package. To avoid malicious use, npm is hanging on to the package name, but loosely, and we'll probably give it to you if you want it.

How can I use simple-spellchecker without fs?

Thanks!

**Comment by jfmdev** [comment]
Hi,

The line `const fs = require('fs')` includes the [built-in Node's File System library](https://nodejs.org/api/fs.html#fs_file_system), i.e. is not including an external library downloaded from _npm_, so you can use it safely.

Regarding the message from https://www.npmjs.com/package/fs, it's a bit misleading, but the real reason why that package name is not available on _npm_ is because Node already has a package called **fs** (and you can't have two packages with the same name).

Regards
